"""
Django settings for tldr project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from .secret_key import SECRET

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRET

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ADMINS = (("TLDR Khabar", "tldrkhabar@gmail.com"),) # In case of production Errors 
MANAGERS = ADMINS

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third Party Apps
    'pyteaser',
    'rest_framework',
    'crispy_forms',
    'social_django',
    'lxml',
    'feedparser',
    'schedule',
    'django_crontab',
    'unidecode',
    # My Apps
    'summarize',
    'login',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'tldr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',

)

WSGI_APPLICATION = 'tldr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# MySQL Database -- During Production
# DATABASES = {
#     'default': {
#         'NAME': 'database_table_name',
#         'ENGINE': 'django.db.backends.mysql',
#         'USER': 'mysql_user',
#         'PASSWORD': 'superS3cret'
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

if DEBUG is False:
    # OAUTH CLIENT ID
    SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'Add your Google OAuth2 Key'
    SOCIAL_AUTH_GITHUB_KEY = 'Add your Github Key'
    SOCIAL_AUTH_TWITTER_KEY = 'Add your Twitter Key'
    SOCIAL_AUTH_FACEBOOK_KEY = 'Add your Facebook Key'

    # OAUTH CLIENT SECRET
    SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Add your Google OAuth2 Secret'
    SOCIAL_AUTH_GITHUB_SECRET = 'Add your Github Secret'
    SOCIAL_AUTH_TWITTER_SECRET = 'Add your Twitter Secret'
    SOCIAL_AUTH_FACEBOOK_SECRET = 'Add your Facebook Secret'
else:
    # OAUTH CLIENT ID
    SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'Add your Google OAuth2 Key'
    SOCIAL_AUTH_GITHUB_KEY = 'Add your Github Key'
    SOCIAL_AUTH_TWITTER_KEY = 'Add your Twitter Key'
    SOCIAL_AUTH_FACEBOOK_KEY = 'Add your Facebook Key'

    # OAUTH CLIENT SECRET
    SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Add your Google OAuth2 Secret'
    SOCIAL_AUTH_GITHUB_SECRET = 'Add your Github Secret'
    SOCIAL_AUTH_TWITTER_SECRET = 'Add your Twitter Secret'
    SOCIAL_AUTH_FACEBOOK_SECRET = 'Add your Facebook Secret'


SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
  'locale': 'en_US',
  'fields': 'id, name, email, age_range'
}
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email',]
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email',]
SOCIAL_AUTH_LOGIN_ERROR_URL = '/settings/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/profile/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static") # Need to change to come over production

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static_dev'),
    # os.path.join(BASE_DIR, "static_in_env"),
    # '/var/www/static/',
)

# CRISPY FORM TAGS SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# DJANGO CRON JOB 
CRONJOBS = [
    ('0 */1 * * *', 'summarize.cron.scheduled_job'),
]


if DEBUG is False:
    # SSL/TLS Security
    CORS_REPLACE_HTTPS_REFERER      = True
    HOST_SCHEME                     = "https://"
    SECURE_PROXY_SSL_HEADER         = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT             = True
    SESSION_COOKIE_SECURE           = True
    CSRF_COOKIE_SECURE              = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS  = True
    SECURE_HSTS_SECONDS             = 1000000
    SECURE_FRAME_DENY               = True
    SECURE_CONTENT_TYPE_NOSNIFF     = True
    SECURE_BROWSER_XSS_FILTER       = True
    SECURE_HSTS_PRELOAD             = True
    X_FRAME_OPTIONS                 = 'DENY'
else:
    # SSL/TLS Security
    CORS_REPLACE_HTTPS_REFERER      = False
    HOST_SCHEME                     = "http://"
    SECURE_PROXY_SSL_HEADER         = None
    SECURE_SSL_REDIRECT             = False
    SESSION_COOKIE_SECURE           = False
    CSRF_COOKIE_SECURE              = False
    SECURE_HSTS_SECONDS             = None
    SECURE_HSTS_INCLUDE_SUBDOMAINS  = False
    SECURE_FRAME_DENY               = False
