# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='summarize_url',
            field=models.TextField(null=True),
        ),
    ]
