# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0003_auto_20170704_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summarize_url',
            field=models.TextField(default='', null=True),
        ),
    ]
