# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0004_auto_20170704_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
