# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0007_rsslinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsslinks',
            options={'verbose_name': 'RSS link', 'verbose_name_plural': 'RSS links'},
        ),
    ]
