# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='ht',
            field=models.BooleanField(default=b'False'),
        ),
        migrations.AddField(
            model_name='login',
            name='nol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='login',
            name='nt',
            field=models.BooleanField(default=b'False'),
        ),
        migrations.AddField(
            model_name='login',
            name='toi',
            field=models.BooleanField(default=b'False'),
        ),
    ]
