# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170730_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='nol',
            field=models.IntegerField(default=5),
        ),
    ]
