# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170812_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='cnn',
            field=models.BooleanField(default=b'True'),
        ),
        migrations.AlterField(
            model_name='login',
            name='ht',
            field=models.BooleanField(default=b'True'),
        ),
        migrations.AlterField(
            model_name='login',
            name='toi',
            field=models.BooleanField(default=b'True'),
        ),
    ]
